from lexicon.lexicon_commands import LEXICON_COMMANDS

LEXICON = {
    '/start': "Привет! Я дневник контроля артериального давления.\n"
              "Я помогаю отслеживать ваши давление, пульс и самочувствие.\n"
              "Врачи рекомендуют заполнять дневники типа меня каждый день.\n"
              "Благодаря мне, врач получит более достоверную информацию о состоянии"
              " вашего здоровья и сможет отметить, в какое время вы находитесь в зоне риска,"
              " и когда вам лучше всего принимать необходимые препараты.\n"
              "Немного о том как вести дневник.\n"
              "Измерять давление лучше утром, в обед и вечером.\n"
              "Желательно указывать общее самочувствие, какие лекарства были приняты\n"
              "Управлять мной можно с помощью кнопки меню, которая внизу или командами:\n"
              f"&#128073; /stop - {LEXICON_COMMANDS['/stop']}\n"
              f"&#128073; /start - {LEXICON_COMMANDS['/start']}\n"
              f"&#128073; /entry - {LEXICON_COMMANDS['/entry']}\n"
              f"&#128073; /timezone - {LEXICON_COMMANDS['/timezone']}\n"
              f"&#128073; /change - {LEXICON_COMMANDS['/change']}\n"
              f"&#128073; /missed - {LEXICON_COMMANDS['/missed']}\n"
              f"&#128073; /send - {LEXICON_COMMANDS['/send']}\n"
              f"&#128073; /doctor – {LEXICON_COMMANDS['/doctor']}\n"
              f"&#128073; /email – {LEXICON_COMMANDS['/email']}\n"
              f"&#128073; /statistics – {LEXICON_COMMANDS['/statistics']}\n"
              f"&#128073; /help – {LEXICON_COMMANDS['/help']}\n"
              f"&#128073; /delete - {LEXICON_COMMANDS['/delete']}\n"
              "Если вдруг я сломаюсь или вы захотите больше узнать обо мне,\n"
              "напишите <a href='cardiobot.100@gmail.com'>cardiobot.100@gmail.com</a>\n"
              "С правилами всё. Для того чтобы получить весь заполненный дневник, необходимо ввести ваш email.\n"
              "Необходимая формальность: отправляя email, вы соглашаетесь на обработку "
              "<a href='https://docs.google.com/document/d/1K0ov9JfTZ8b2UxLseGRQu4ZKyLi29Hymsk6TGO-Dw_0/edit?usp=sharing'>данных</a>.",
    '/help': f"&#128073; /stop - {LEXICON_COMMANDS['/stop']}\n"
             f"&#128073; /start - {LEXICON_COMMANDS['/start']}\n"
             f"&#128073; /entry - {LEXICON_COMMANDS['/entry']}\n"
             f"&#128073; /timezone - {LEXICON_COMMANDS['/timezone']}\n"
             f"&#128073; /change - {LEXICON_COMMANDS['/change']}\n"
             f"&#128073; /missed - {LEXICON_COMMANDS['/missed']}\n"
             f"&#128073; /send - {LEXICON_COMMANDS['/send']}\n"
             f"&#128073; /doctor – {LEXICON_COMMANDS['/doctor']}\n"
             f"&#128073; /email – {LEXICON_COMMANDS['/email']}\n"
             f"&#128073; /statistics – {LEXICON_COMMANDS['/statistics']}\n"
             f"&#128073; /help – {LEXICON_COMMANDS['/help']}\n"
             f"&#128073; /delete - {LEXICON_COMMANDS['/delete']}"
}

