version: '3.1'

services:
  bot:
    container_name: cardio_bot
    build:
      context: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - EMAIL=${EMAIL}
      - EMAIL_PASS=${EMAIL_PASS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: cardio_bot_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: cardio_bot_redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command:
      - redis-server

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres-data:
  redis-data:


