version: '3.1'

services:
  db:
    image: postgres:15-alpine
    container_name: db_dev
#    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_dev
#    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command:
      - redis-server

  adminer:
     image: adminer
     container_name: adminer_dev
#     restart: always
     ports:
       - "8080:8080"

volumes:
  postgres-data:
  redis-data:


