"""new_models2

Revision ID: 87febb90b671
Revises: 6f7d391437c2
Create Date: 2024-02-24 11:29:09.947384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87febb90b671'
down_revision: Union[str, None] = '6f7d391437c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('person_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_data_person_id_fkey', 'user_data', type_='foreignkey')
    op.create_foreign_key(None, 'user_data', 'people', ['person_user_id'], ['id'])
    op.drop_column('user_data', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_data', type_='foreignkey')
    op.create_foreign_key('user_data_person_id_fkey', 'user_data', 'people', ['person_id'], ['id'])
    op.drop_column('user_data', 'person_user_id')
    # ### end Alembic commands ###
