"""new_models

Revision ID: 6f7d391437c2
Revises: 40d13cc420ee
Create Date: 2024-02-24 08:50:00.241395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f7d391437c2'
down_revision: Union[str, None] = '40d13cc420ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('arrhythmia', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_id'), 'user_data', ['id'], unique=False)
    op.drop_column('people', 'arrhythmia')
    op.drop_column('people', 'comment')
    op.drop_column('people', 'pulse')
    op.drop_column('people', 'diastolic')
    op.drop_column('people', 'systolic')
    op.drop_column('people', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('systolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('diastolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('pulse', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('arrhythmia', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_data_id'), table_name='user_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
