"""new_models4

Revision ID: 62e778d6983a
Revises: e2a8a356c863
Create Date: 2024-02-24 16:13:55.977626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e778d6983a'
down_revision: Union[str, None] = 'e2a8a356c863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_data_person_user_id_fkey', 'user_data', type_='foreignkey')
    op.create_foreign_key(None, 'user_data', 'people', ['person_id'], ['id'])
    op.drop_column('user_data', 'person_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('person_user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_data', type_='foreignkey')
    op.create_foreign_key('user_data_person_user_id_fkey', 'user_data', 'people', ['person_user_id'], ['id'])
    op.drop_column('user_data', 'person_id')
    # ### end Alembic commands ###
